### PR TITLE
update bundle and postgres lib

### PR DESCRIPTION
**Pull request by kian99**
# Description

When testing the machine charm I found a few things that needed to be updated:
- The bundle was installing Livepatch from `ops1.x/edge`. The charm is now available from `ops1.x/stable` so the bundle has been updated.
- The machine constraints on the bundle were quite low so those have been bumped up.
- There was a deprecation warning when running Juju actions (see below) updated the charm for this.
```
/var/lib/juju/agents/unit-livepatch-0/charm/./src/charm.py:530: DeprecationWarning: Calling `ops.main.main()` is deprecated, call `ops.main()` instead
  main(OperatorMachineCharm)
```
Additionally, I updated the postgres charm library.

### CODE REVIEW

**Review by alesstimec — DISMISSED** [review]

**Review by SimoneDutto — COMMENTED** [review]
Do you reckon we need this much RAM with golang? Why do we have 50G of disk? Are we assuming the use filesystem as the patch backend?

**Comment by kian99** [comment]
@SimoneDutto by default, yes, the patches go on the filesystem.

**Comment by SimoneDutto** [comment]
> @SimoneDutto by default, yes, the patches go on the filesystem.

i think that for a bundle the constraints are pretty high. But if you think it is easy to override/doesn't matter i am happy to approve

**Comment by kian99** [comment]
> > @SimoneDutto by default, yes, the patches go on the filesystem.
> 
> i think that for a bundle the constraints are pretty high. But if you think it is easy to override/doesn't matter i am happy to approve

It is fairly easy to override them, but we should have a good default. I think 2 cores and 4GB is still quite cheap conceptually. So I'm happy to leave it as is.

**Review by SimoneDutto — APPROVED** [review]

**Review by SimoneDutto — APPROVED** [review]

**Pull request merged**
